### ISSUE TITLE
No semicolon at end of file

### ISSUE THREAD

**Issue by fr-animal** [akatov/angular-contenteditable#38]
Its trivial, but it causes concat scripts to mess things up.

**Comment by jeremythille** [comment]
+1, this problem drove me crazy. My app stopped working, with a weird message "Uncaught TypeError: angular.module(...).directive(...) is not a function"

This was caused by contentEditable not having a semicolon at the end, and being concatenated with another directive.

**Comment by grammka** [comment]
Common mistake... fix this plz!

**Comment by haffmaestro** [comment]
This has been fixed, with the bower version 0.3.8, make sure you have the right one
