### ISSUE TITLE
Need someone to help maintain / take over the project

### ISSUE THREAD

**Issue by akatov** [akatov/angular-contenteditable#42]
Unfortunately my work commitments don't leave me much time to carry on work on this project. I'm looking for volunteers to help me maintain it / take over development.

**Comment by haffmaestro** [comment]
I'll take over! Using this in production of a major project, and need to update it! Would be honored to take-over.

**Comment by akatov** [comment]
@haffmaestro I've given you push access. Thank you for helping out.

**Comment by haffmaestro** [comment]
@akatov No problem! I pushed new tags just this morning to update the bower!
